### PR TITLE
[feature] add webp support

### PR DESCRIPTION
**Pull request by ftrvxmtrx**
I have a PR for gts as well, wonder if it makes more sense to make it with a exif-terminator bump once this PR is merged.

### CODE REVIEW

**Comment by tsmethurst** [comment]
Love how this looks so far, thank you! One question: i know v. little about webp; does it also store rotation data inside exif, like jpeg does? If so, will this PR preserve that rotation data? One of the issues I had with this library a while ago was dropping rotation data, and having people's images turn up sideways when they oughtn't, so I'd like to avoid reintroducing that bug, if possible.

**Comment by ftrvxmtrx** [comment]
@tsmethurst no, unfortunately it *is* possible exif _might_ contain rotation, which isn't taken into account with this PR. If required (and when I have more free time) I can rework both jpg and webp terminators so they use a common logic (split out of jpg one) to work with that.

**Comment by ftrvxmtrx** [comment]
@tsmethurst interesting: https://zpl.fi/exif-orientation-in-different-formats/
See webp section there. Seems like leaving rotation in EXIF wouldn't make a difference (at least with Firefox :/).

**Comment by tsmethurst** [comment]
Alright, thanks for investigating! Let's just merge it then, and we'll iron out any problems it might cause in GtS later ;)

**Comment by ftrvxmtrx** [comment]
@tsmethurst as a follow up - does exif-terminator need a new release for it to get bumped in gts repo?

**Comment by tsmethurst** [comment]
Yeah, it does! I got sidetracked by other stuff (doing rc2 for gts). I'll release tomorrow :)

**Pull request merged**
